### ISSUE TITLE
404 Not Found

### ISSUE THREAD

**Issue by Ranae** [AmeliaMN/shiny-server#1]
Obviously not a super-important issue here, but I was going to send the blog to some one who is called the wrong name all the time and it looks like your server is not working. Just thought you'd like to know, if you didn't already.

**Comment by AmeliaMN** [comment]
Whoops, thanks for letting me know! I switched from DigitalOcean to shinyapps.io because I wasn't using other DO features. The app is live here: https://ameliamn.shinyapps.io/Amanda/

**Comment by Ranae** [comment]
Thanks! Solved my life-long curiosity of why people always call me Rachel. About 25% of R-girls from the 80s are Rachels and only .04% are Ranae.
